services:

  kulzzy-server-api:

    container_name: kulzzy-server-api

    build: .

    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:

      TZ: Africa/Lagos

      KULZZY_STORAGE_ROOT: /kulzzy

      KULZZY_AUTH_DB: /kulzzy/auth/kulzzy_auth.db

    volumes:

      - /srv/kulzzy:/kulzzy
