services:

  kulzzy-server-api:

    container_name: kulzzy-server-api

    build: .

    restart: unless-stopped

    ports:
      - "5000:5000"

    environment:

      TZ: Africa/Lagos

      KULZZY_STORAGE_ROOT: /kulzzy

      KULZZY_API_KEY: ${KULZZY_API_KEY}

    volumes:

      - /srv/kulzzy/audio:/kulzzy/audio

      - /srv/kulzzy/celebrants:/kulzzy/celebrants

      - /srv/kulzzy/websites:/kulzzy/websites

      - /srv/kulzzy/repositories:/kulzzy/repositories

      - /srv/kulzzy/uploads:/kulzzy/uploads

      - /srv/kulzzy/backups:/kulzzy/backups
