// =====================================================
// KULZZY RADIO DNS ZONE
// VERSION 1.0
// =====================================================

zone "kulzzyradio.com" {

    type master;

    file "/srv/kulzzy/dns/zones/kulzzyradio.com.zone";

    allow-query {
        any;
    };

    allow-transfer {
        none;
    };

    notify no;
};
